spring:
  datasource:
    url: jdbc:mysql://10.38.128.81:3306/encdata_soa_sddata?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: guide
    password: guide
    driver-class-name: com.mysql.jdbc.Driver